# Site settings
title: Rohit Kumar CV
name: Rohit Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://www.tutre.com/
 - title: GitHub
   url: https://github.com/rrohitramsen
 - title: Medium
   url: https://medium.com/@rrohit.ramsen
 - title: LinkedIn
   url: https://www.linkedin.com/in/rohit-kumar-76622116/

#Any buzzword skills you want to include
skills:
 - Java
 - Apache Spark
 - Apache Kafka
 - Spring Boot
 - Data Structure & Algorithm
 - AWS - EC2, SQS, Elastic Cache, EMR, SQS, S3, Lamda
 - Scala
 - Data Streaming
 - Serverless
 - REST
 - Mysql
 - Mongo DB
 - Neo4j
 - Cassandra
 - Software Design & Development
 - Microservices
 - Git
 - Social Graph
 - Recommender System
 - Jira
 - Jenkins

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://www.tutre.com/

#Work experience is required
roles:
 - title: Associate Technology Specialist
   start: Feb 2017
   end: Ongoing
   employer: Synechron Technologies(London Stock Exchange Group, UBS)
   description: Developed Push Notification on API using AWS Redis Pub Sub and achieved real time updates for clients and reduced data base load.
                Developed Authentication Service using AWS Cognito JWT which is used in securing and authorising other micro services
                Developed static data cache using AWS Elastic Cache which improved application startup time and optimised static data loading.
                Developed low cost and Server-less data pipeline using AWS lamda, S3 and SQS
                Developed and Standardise API request, response, logging, status and response codes. Which helped in improving communication b/w API and clients, ease of integration and improved tracking of issues and status.
                Developed Entity Management framework. Which helped in reducing testing and development effort of static data rest APIs by 60% and also enforces Restful APIs best practices.
                Developed Junit template for rest APIs. Which helped in reducing development effort for other rest APIs and also improved code coverage.
                Consulted with project managers and clients regarding optimal architecture and solutions to utilise in project development
                Worked on MiFID􀆸 II regulatory requirements. Developed front office eligibility micro service.
                Streamlined the Json schemas for all DTOs for the project and replaced all java DTO and aligned the APIs with Json schema generated DTOs.
                Developed and presented POC on data streaming job using Kafka, Spark and Cassandra.
 - title: Technology Lead
   start: Feb 2016
   end: Dec 2016
   employer: Ephesoft Inc.
   description: Universe Analytics - Extract meaning from unstructured content to predict future value of investments, identify fraud, enable eDiscovery, uncover new opportunities, and make informed decisions.
                Designed & Developed Data Relationship, Data Quality and Data Streaming Jobs using Apache Spark, Kafka, Graph, Mongo DB and Java.
                Data relationship job creates undirected graph of documents which helps in creating relationships, performing queries and driving new relationships between the documents. This graph plays key role in driving other changes on platform.
                Designed & Developed Automation testing framework which helped the testing team in computing page per minute stats for the application
 - title: Freelancing
   start: June 2014
   end: Jan 2016
   employer: Farlex Pharmaceuticals Pvt. Ltd
   description: Researched and developed good understanding of social graph, graph database, and recommender system
                Designed & Developed recommendation service, this service feeds the user with friends and other data based on the user social graph
                Used Neo4j graph database to store user social graph and to recommend users
                Designed and developed user profile service, user service, and user graph service
 - title: Software Engineer
   start: July 2012
   end: June 2014
   employer: RBS India Development Centre, Gurgaon
   description: Developed new applications, components, and functionality to existing systems
                Involved in accurately providing estimated development times
                Developed new functionalities, both back-end and front-end
                Analyzed data and conducted compatibility/ quality assurance testing
                Investigated alternate solutions and implemented better solutions
 - title: Software Engineer
   start: Oct 2010
   end: July 2012
   employer: Aricent Group, Gurgaon
   description: Designed and developed S6a and Sh interface based on standards and specifications such as 3GPP, LTE, and IMS using Java
                Designed and implemented test cases using JUnit
                Designed Detailed Function Specification (DFS), Unit Test Plan (UTP), and Integration Test Plan (ITP)
                Engaged in code review, configuration, and installation of HSS on UNIX/ Solaris machine
                Assisted team members on their assigned tasks

#Education is required
education:
- level: Master of Computer Application (MCA)
  date: 2010
  subject: Programming, Design, Data Structure & Algorithms
  school: Maharshi Dayanand University
- level: Bachelor of Science Computer Application (B.Sc. CA) 
  date: 2007
  subject: C, Data base and Computer Science
  school: Kurukshetra University Kurukshetra

#List of interesting Github repo/projects to include - optional
github:
 - rrohitramsen/firehose
 - rrohitramsen/spring-boot-oauth2-jwt-swagger-ui
 - rrohitramsen/gameoflife
 - rrohitramsen/ems
 - rrohitramsen/aws_jwt_cognito
 - rrohitramsen/JPStockMarketRepository
 - rrohitramsen/ticket_system
 - rrohitramsen/returns_calculator
 - rrohitramsen/dynamic_programming
 - rrohitramsen/Graph
 - rrohitramsen/recursion

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Apache Spark and Kafka </strong>: I am experienced in Apache Spark and Kafka and developed data streaming, data quality and data realtionships jobs. <br/><br/>
